language: php

php:
  - '5.6'
  - '7.0'

before_script: cd app && composer install && cd ..

script: phpunit -c app/phpunit.xml.dist --coverage-text

notifications:
  email:
    - hallo@dionsnoeijen.nl