language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script: cd app && composer install

script: phpunit phpunit -c app/phpunit.xml.dist --coverage-text

notifications:
  email:
    - hallo@dionsnoeijen.nl