version: "2"
services:
  blog:
    build:
      context: ./docker/blog
    container_name: blog
    image: dionsnoeijen/blog:latest
    depends_on:
      - php_fpm
      - mysql
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/blog/app:/var/www/blog
    links:
      - php_fpm
      - mysql
  php_fpm:
    build:
      context: ./docker/php
    image: dionsnoeijen/php_fpm:latest
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.1.17"
      PHP_IDE_CONFIG: "serverName=blog.dev"
    container_name: php_fpm
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./docker/blog/app:/var/www/blog
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog