version: "2"
services:
  blog:
    build: ./dockerfile/blog
    container_name: blog
    depends_on:
      - php
      - mysql
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /Users/dionsnoeijen/www/blog/app:/var/www/blog
    links:
      - php
      - mysql
  php:
    build: ./dockerfile/php
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.1.17"
      PHP_IDE_CONFIG: "serverName=blog.dev"
    container_name: php
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /Users/dionsnoeijen/www/blog/app:/var/www/blog
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog