version: "2"
services:
  blog:
    build:
      context: ./docker/experimentation
    container_name: experimentation
    image: dionsnoeijen/experimentation:latest
    depends_on:
      - php_fpm
      - mysql
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/experimentation/app:/var/www/experimentation
    links:
      - php_fpm
      - mysql
  php_fpm:
    build:
      context: ./docker/php_fpm
    image: dionsnoeijen/php_fpm:latest
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.1.17"
      PHP_IDE_CONFIG: "serverName=experimentation.dev"
    container_name: php_fpm
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./docker/experimentation/app:/var/www/experimentation
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: experimentation
      MYSQL_USER: experimentation
      MYSQL_PASSWORD: experimentation